"$schema" = "https://starship.rs/config-schema.json"

[character]
vicmd_symbol = "[](green)"

[git_branch]
symbol = " "

[git_status]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[rust]
symbol = " "
style = "bold #e55e2f"

[python]
symbol = " "
pyenv_version_name = true

[golang]
symbol = " "

[zig]
symbol = " "

[lua]
symbol = " "
style = "bold #51a0cf"

[nodejs]
detect_files = ["package.json", ".node-version", "!bun.lock", "!bun.lockb", "!bunfig.toml"]

[bun]
detect_files = ["bun.lock", "bun.lockb", "bunfig.toml", "!package-lock.json"]
